### ISSUE TITLE
question: why does mobile() also return tablets?

### ISSUE THREAD

**Issue by daedelus-j** [hgoebl/mobile-detect.js#19]
so i was bitten recently because i didn't RTFM:
![](http://note.io/1JmH3vd)

but why have a `mobile()` and a `tablet()` method if mobile also returns tablet?

**Comment by daedelus-j** [comment]
@hgoebl

**Comment by hgoebl** [comment]
Thanks for your feedback. You can see `mobile()` as a short form of `phoneOrTablet()`. If you are interested in more details you can use `phone()` and/or `tablet()`.

@daedelus-j do you have a suggestion how to change the API?

And what would you expect when calling `mobile()`? Returning a falsy value when it's a tablet? A tablet is a mobile device, isn't it?

**Comment by bhamodi** [comment]
@hgoebl - A tablet is a mobile device, yes. However, for most use cases, tablets are to be treated/rendered differently due to their much larger screen resolutions.

I'd personally recommend differentiating between the two using something like: `is_tablet()` and `is_phone()`. Additionally, `is_mobile()` should yield true for BOTH phones and tablets. :+1:

**Comment by hgoebl** [comment]
@bhamodi that's exactly the case: `phone()` is truthy for phones, `tablet()` is truthy for tablets and `mobile()` is truthy for both. So I don't know what could/should be changed in the existing API.
