### ISSUE TITLE
Mobile Chrome on unknown tablet not detected as mobile

### ISSUE THREAD

**Issue by jbesta** [hgoebl/mobile-detect.js#24]
## Problem

Hi,

today i've run into trouble detecting Praktica tablet (TP750 3GGSM) as unknown tablet - or generally speaking as a mobile device - in Google Chrome (v39.0.2171.93) on Android 4.0.4.

User agent string reported by Chrome:

`Mozilla/5.0 (Linux; Android 4.0.4; TP750 3GGSM Build/IMM76I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Safari/537.36`

After investigating for a while I've figured out that the problem is in **detectMobileBrowsers.fullPattern** regular expression. According to documentation at https://developer.chrome.com/multidevice/user-agent UA string on Android contains **Mobile** keyword only for phones and not for tablets.

## Possible solution

Possible solution would be to modify regular expression from:

`/(android|bb\d+|meego).+mobile|...`

to

`/(android|bb\d+|meego).+(mobile)?|...`

if it does not any have side effects.

**Comment by hgoebl** [comment]
@jbesta thanks for the deep information and the solution proposal. I have to think about a way how it's possible to change such basic behaviour and not to break current usages of the library. It's really hell when you count on a particular (tested) behaviour and then it changes because you update and only want to have new devices detected.

**Comment by hgoebl** [comment]
This problem is fixed with v1.2.0.
An additional pattern has been added for unknown tablets (`/android/` when `android.*mobile` didn't match).


Output of [check](http://hgoebl.github.io/mobile-detect.js/check/):

Result:
phone()
-
tablet()
UnknownTablet
mobile()
UnknownTablet
os()
AndroidOS
userAgent()
Chrome
mobileGrade()
A
