### ISSUE TITLE
Destructured usage

### ISSUE THREAD

**Issue by prescottprue** [hgoebl/mobile-detect.js#56]
If attempting to use destructuring when creating constructor like this:
```js
const { os, userAgent } = new MobileDetect(window.navigator.userAgent);
```
The following error is thrown:

<img width="429" alt="screen shot 2017-01-10 at 12 56 23 pm" src="https://cloud.githubusercontent.com/assets/2992224/21824432/3bf11650-d734-11e6-95bd-0b29ab45558a.png">

It seems to be due to `this` being undefined when checking for the cache. A small check for the existence of `this` should fix the problem, but then I think it will no longer use the cache.

Will attempt a PR sometime soon.

**Comment by hgoebl** [comment]
`os` and `userAgent` aren't properties, but methods.
What you get are function pointers without the `this` context of the created MobileDetect object.
IMO we don't need a PR for this. It's just used in a wrong way. Or I am missing anything here?

**Comment by prescottprue** [comment]
Thanks for responding so quickly!

Yes agreed, they are methods, but is there not a way to check for existence of "this" so that methods can be used in this fashion?

When used they are used like so:
```js
const { os } = new MobileDetect(window.navigator.userAgent);
os()
// would be equivalent to
const md = new MobileDetect(window.navigator.userAgent);
md.os()
```

Totally cool if this usage is not going to be supported, but it might be nice to note that somewhere in the docs.

**Comment by hgoebl** [comment]
This usage cannot be supported easily and would have great impact on every method.

It's a very common problem which is unbelievable for OOP programmers coming from Java, C++, C#. Probably JavaScript is the only language having this issue. In Java it's not possible to pass a reference to a non-static method and call it without the object.

http://yehudakatz.com/2011/08/11/understanding-javascript-function-invocation-and-this/

I'll close this issue since I regard this a problem of understanding the language and its usage.

**Comment by prescottprue** [comment]
It was easy enough for me to "understand" that I couldn't use it that way (as I have experience with `this` and its usage), but it might not be for others in the future. Since javascript has the capability to allow people to access things this way (and is becoming even more common), it might be nice to just mentioned that it will not work as expected.

Thanks for the response.
